import json
import os
from pathlib import Path

def classify_from_path(picture_path):
    """Extract classification from file path according to the full hierarchy"""
    path_parts = str(picture_path)
    print(path_parts)
    
    # Initialize classification fields
    classification = {
        "c1": None,
        "c2": None,
        "c3": None,
        "file_path": str(picture_path)
    }

    # 1. Variable branch
    if any(x in path_parts for x in ["AGN", "Cepheid", "RRL", "d-Sct", "EB"]):
        classification["c1"] = "Variable"

        # 1.1 AGN

        if "ELASTICC_TRAIN_AGN" in path_parts:
            classification["c2"] = "AGN"
        
        # 1.2 Periodic sub-branch
        else:
            classification["c2"] = "Periodic"
            
            if "Cepheid" in path_parts:
                classification["c3"] = "Cepheid"
            elif "RRL" in path_parts:
                classification["c3"] = "RR Lyrae"
            elif "d-Sct" in path_parts:
                classification["c3"] = "Delta Scuti"
            elif "EB" in path_parts:
                classification["c3"] = "Eclipsing Binary"
    # 2. Transient branch
    else:
        classification["c1"] = "Transient"
        
        # 2.1 Supernova sub-branch
        if "Supernova" in path_parts or any(x in path_parts for x in ["SNIa", "SNIax", "SNIb", "SNIc","SNII"]):
            classification["c2"] = "Supernova"
            
            if "SNIax" in path_parts:
                classification["c3"] = "Type Iax"
            elif "SNIa" in path_parts:
                classification["c3"] = "Type Ia"
            elif "SNIb" in path_parts or "SNIc" in path_parts:
                classification["c3"] = "Type Ib/c"
            elif "SNII" in path_parts:
                classification["c3"] = "Type II"
        
        # 2.2 Short sub-branch
        elif "Short" in path_parts or any(x in path_parts for x in ["Mdwarf", "KN", "uLens", "dwarf-nova"]):
            classification["c2"] = "Short"
            
            if "Mdwarf" in path_parts:
                classification["c3"] = "M dwarf flares"
            elif "KN" in path_parts:
                classification["c3"] = "KN"
            elif "uLens" in path_parts:
                classification["c3"] = "uLens"
            elif "dwarf-nova" in path_parts:
                classification["c3"] = "Dwarf Nova"
        
        # 2.3 Long sub-branch
        else:
            classification["c2"] = "Long"
            
            if "SLSN" in path_parts:
                classification["c3"] = "SLSN"
            elif "PISN" in path_parts:
                classification["c3"] = "PISN"
            elif "TDE" in path_parts:
                classification["c3"] = "TDE"
            elif "CART" in path_parts:
                classification["c3"] = "CART"
            elif "ILOT" in path_parts:
                classification["c3"] = "ILOT"
    
    return classification

def generate_prompts(image_path,lightcurve_data=None):
    """
    Generate prompts in JSONL format with classification
    
    Args:
        image_path: image file paths
        output_file: Path to output JSONL file
        lightcurve_data: Optional dict mapping paths to lightcurve data
    """
    output_file = '/home/share/guofangkeda/wangcunshi/LSST/jsonl/prompts.jsonl'
    output_dir = Path(output_file).parent
    output_dir.mkdir(parents=True, exist_ok=True)


    
    
    with open(output_file, 'a',encoding='utf-8') as f:
        # Get classification
        classification = classify_from_path(image_path)
        
        # Format classification string
        class_str = ", ".join(filter(None, [
            classification["c1"],
            classification["c2"],
            classification["c3"]
        ]))
    
        
        # Create prompt
        prompt = {
            "query": (
                "This is a Lomb-Scargle periodogram generated by flux of a lightcurve "
                "from Large Synoptic Survey Telescope (LSST). Please determine the "
                "classification of this object hierarchically. We provide the lightcurve "
                "as well here."
                "Please think step by step and provide the result."
            ),
            "response": class_str,
            "images": [str(image_path)]
        }
        print(prompt)

        
        f.write(json.dumps(prompt,ensure_ascii=False) + '\n')



if __name__ == '__main__':
    # ... [之前的遍历文件夹和创建目录的逻辑保持不变]

    # # 使用所有可用CPU核心数的一半作为进程池大小
    # num_processes = cpu_count() // 2
    # pool = Pool(processes=num_processes)

    # tasks = []
    phot_root = r'/home/share/guofangkeda/wangcunshi/LSST/Picture of Lombscargle/LS'
    
    for folder_name in os.listdir(phot_root):
        folder_path = os.path.join(phot_root, folder_name)# AGN

        for subfolder_name in os.listdir(folder_path):
            subfolder_path = os.path.join(folder_path, subfolder_name) #AGN 001
      

            for file_name in os.listdir(subfolder_path):
                file_path = os.path.join(subfolder_path, file_name) # AGN 001 8094
                # tasks.append((file_path, output_subfolder))
                for picture_name in os.listdir(file_path):
                    picture_path = os.path.join(file_path, picture_name)
                    generate_prompts(picture_path, lightcurve_data=None)
                    # print(classify_from_path(picture_path))



              
                    
                    

